### DISCUSSION TITLE
Entitiy availability

### DISCUSSION THREAD

**Discussion by farmio** [XKNX/knx-integration#21] [General]
### Context

Due to lack of support for lock / read-only entity status in Home Assistant (what DPT 2 is commonly used for in KNX) we should find an alternative approach to reflect that somehow. Eg. when a cover is locked, but a move-telegram is received, we can't know if it is actually moving.

### Proposal

Add an optional `availability` key for knx entities allowing to configure one or multiple group addresses (DPT 1 or 2) to allow setting the availability property of a KNX entity.

```yaml
knx:
  light:
    - address: 1/1/1
      ...
      availability:
        - state_address: 4/4/4
          type: 2
          available_payload: 0
```

### Considerations

- The locked state couldn't be differentiated from disconnected state
