### ISSUE TITLE
Add watchdog to set sensor state to unavailable on missing telegrams

### ISSUE THREAD

**Issue by shurli** [XKNX/knx-integration#11]
Hi @farmio,
This is a feature suggest.

Sometimes KNX devices fail or their connection get lost due to environmental issues. e.g. weather station, animals, ... or are badly designed and gets stuck. In these cases no more WriteTelegrams wether value-changed-triggered or cyclic will be received.
For now the sensor entity state will stay on its last value forever or at least till a HA restart when it gets "unknown" due to a failing initial read.

I would like to see a "watchdog" or "timeout" config option to set a duration in which a telegram needs to get received otherwise the entity state will change to "unavailable".
This state change could then be used to trigger problem notifications or bring systems in fail-safe-modes.

I think the code to implement the feature is pretty the same like in the sync_state: expire function.
There is also a timer listening to the WriteTelegrams and in case fires the ReadTelegram.

Like to here your response on this idea.
Lg shurli

**Comment by shurli** [comment]
For users who are interested in knx sensor watchdog:

Here is a common script for a watchdog in HA on entity level:
[https://community.home-assistant.io/t/watchdog-automation-script-for-checking-on-sensors/174628/1](https://community.home-assistant.io/t/watchdog-automation-script-for-checking-on-sensors/174628/1)

With the latly introduced "last_reported" attribute, this should be very usable.
[https://developers.home-assistant.io/blog/2024/03/20/state_reported_timestamp/](https://developers.home-assistant.io/blog/2024/03/20/state_reported_timestamp/)

**Comment by farmio** [comment]
You can always use `knx.telegram` trigger to watch for telegrams by individual addresses, rather than group addresses - which might be closer to a Knx device watchdog data source.

**Comment by shurli** [comment]
Yes, currently I am experimenting with this triggered template sensor, which saves the last timestamps in an attributes dict.

```
template:
  - triggers:
      - trigger: knx.telegram
        group_value_write: true
        group_value_response: true
        group_value_read: false
        incoming: true
        outgoing: false

    sensor:
      - name: "Last Telegram"
        state: ""
        attributes:
          source: >
            {% set current = this.attributes.get('source', {}) %}
            {% set new = {trigger.source: trigger.timestamp}  %}
            {{ combine(current, new) }}
```

output of 

`{{ states.sensor.last_telegram.attributes.source }}`

gives this:

```
{
  "3.1.5": "2025-05-20T15:46:40.058885+02:00",
  "3.2.23": "2025-05-20T15:44:43.662517+02:00",
  "1.1.200": "2025-05-20T15:46:44.946093+02:00",
  "3.1.15": "2025-05-20T15:45:01.534198+02:00",
  "3.2.3": "2025-05-20T15:29:09.780714+02:00",
  "4.1.100": "2025-05-20T15:45:02.965331+02:00",
  "3.2.5": "2025-05-20T15:29:10.401146+02:00",
  "3.2.22": "2025-05-20T15:45:48.729737+02:00",
  "4.1.6": "2025-05-20T15:46:43.463920+02:00"
}
```

now a have to compare these timestamps with a maximum allowed timespan per device to get "faulty" devices
